// <auto-generated />
namespace Borto_v1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class Converting : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Converting));
        
        string IMigrationMetadata.Id
        {
            get { return "202005252144483_Converting"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
