//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Borto_v1.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Borto_v1.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        public static string Account {
            get {
                return ResourceManager.GetString("Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account_Page.
        /// </summary>
        public static string Account_Page {
            get {
                return ResourceManager.GetString("Account_Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added to favorites!.
        /// </summary>
        public static string Added_to_favorites {
            get {
                return ResourceManager.GetString("Added_to_favorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin.
        /// </summary>
        public static string Admin {
            get {
                return ResourceManager.GetString("Admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin Page.
        /// </summary>
        public static string Admin_Page {
            get {
                return ResourceManager.GetString("Admin_Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I agree with terms of use of the application.
        /// </summary>
        public static string AgreementTermOfUse {
            get {
                return ResourceManager.GetString("AgreementTermOfUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        public static string Change_Password {
            get {
                return ResourceManager.GetString("Change_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose.
        /// </summary>
        public static string Choose {
            get {
                return ResourceManager.GetString("Choose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        public static string Comment {
            get {
                return ResourceManager.GetString("Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment Deleted.
        /// </summary>
        public static string Comment_Deleted {
            get {
                return ResourceManager.GetString("Comment_Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments.
        /// </summary>
        public static string Comments {
            get {
                return ResourceManager.GetString("Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data saved successfully.
        /// </summary>
        public static string Data_saved_successfully {
            get {
                return ResourceManager.GetString("Data_saved_successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Upload:.
        /// </summary>
        public static string DateUpload {
            get {
                return ResourceManager.GetString("DateUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        public static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Page.
        /// </summary>
        public static string Download_Page {
            get {
                return ResourceManager.GetString("Download_Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration:.
        /// </summary>
        public static string Duration {
            get {
                return ResourceManager.GetString("Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorite.
        /// </summary>
        public static string Favorite {
            get {
                return ResourceManager.GetString("Favorite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorite Videos.
        /// </summary>
        public static string Favorite_Videos {
            get {
                return ResourceManager.GetString("Favorite_Videos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder.
        /// </summary>
        public static string Folder {
            get {
                return ResourceManager.GetString("Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home Page.
        /// </summary>
        public static string Home_Page {
            get {
                return ResourceManager.GetString("Home_Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect old password.
        /// </summary>
        public static string Incorrect_old_password {
            get {
                return ResourceManager.GetString("Incorrect_old_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IncorrectData.
        /// </summary>
        public static string IncorrectData {
            get {
                return ResourceManager.GetString("IncorrectData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert your comment here.
        /// </summary>
        public static string Insert_your_comment_here {
            get {
                return ResourceManager.GetString("Insert_your_comment_here", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Long first.
        /// </summary>
        public static string Long_first {
            get {
                return ResourceManager.GetString("Long_first", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Videos.
        /// </summary>
        public static string MyVideos {
            get {
                return ResourceManager.GetString("MyVideos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name (required).
        /// </summary>
        public static string Name_required {
            get {
                return ResourceManager.GetString("Name_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New first.
        /// </summary>
        public static string New_first {
            get {
                return ResourceManager.GetString("New_first", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password.
        /// </summary>
        public static string New_Password {
            get {
                return ResourceManager.GetString("New_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nickname.
        /// </summary>
        public static string NickName {
            get {
                return ResourceManager.GetString("NickName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No internet connection.
        /// </summary>
        public static string No_internet_connection {
            get {
                return ResourceManager.GetString("No_internet_connection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old first.
        /// </summary>
        public static string Old_first {
            get {
                return ResourceManager.GetString("Old_first", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old Password.
        /// </summary>
        public static string Old_Password {
            get {
                return ResourceManager.GetString("Old_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password changed.
        /// </summary>
        public static string Password_changed {
            get {
                return ResourceManager.GetString("Password_changed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player.
        /// </summary>
        public static string Player {
            get {
                return ResourceManager.GetString("Player", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post date.
        /// </summary>
        public static string Post_Date {
            get {
                return ResourceManager.GetString("Post_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removed from favorite!.
        /// </summary>
        public static string Removed_from_favorite {
            get {
                return ResourceManager.GetString("Removed_from_favorite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a picture for your icon.
        /// </summary>
        public static string Select_A_Picture {
            get {
                return ResourceManager.GetString("Select_A_Picture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a picture for your video.
        /// </summary>
        public static string Select_a_picture_for_your_video {
            get {
                return ResourceManager.GetString("Select_a_picture_for_your_video", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Error: .
        /// </summary>
        public static string ServerError {
            get {
                return ResourceManager.GetString("ServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Short first.
        /// </summary>
        public static string Short_first {
            get {
                return ResourceManager.GetString("Short_first", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SIGN IN.
        /// </summary>
        public static string SignIn {
            get {
                return ResourceManager.GetString("SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in to your account.
        /// </summary>
        public static string SignInTitle {
            get {
                return ResourceManager.GetString("SignInTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SIGN UP.
        /// </summary>
        public static string SignUp {
            get {
                return ResourceManager.GetString("SignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign up.
        /// </summary>
        public static string SignUpTitle {
            get {
                return ResourceManager.GetString("SignUpTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source.
        /// </summary>
        public static string Source {
            get {
                return ResourceManager.GetString("Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This login is already exist.
        /// </summary>
        public static string This_login_is_already_exist {
            get {
                return ResourceManager.GetString("This_login_is_already_exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to show/hide interface use key &apos;I&apos;.
        /// </summary>
        public static string to_show_hide_interface_use_key {
            get {
                return ResourceManager.GetString("to_show_hide_interface_use_key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload.
        /// </summary>
        public static string Upload {
            get {
                return ResourceManager.GetString("Upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Page.
        /// </summary>
        public static string Upload_Page {
            get {
                return ResourceManager.GetString("Upload_Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Date.
        /// </summary>
        public static string UploadDate {
            get {
                return ResourceManager.GetString("UploadDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Nickname.
        /// </summary>
        public static string User_NickName {
            get {
                return ResourceManager.GetString("User_NickName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video.
        /// </summary>
        public static string Video {
            get {
                return ResourceManager.GetString("Video", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video Deleted.
        /// </summary>
        public static string Video_Deleted {
            get {
                return ResourceManager.GetString("Video_Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video Page.
        /// </summary>
        public static string Video_Page {
            get {
                return ResourceManager.GetString("Video_Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video Player.
        /// </summary>
        public static string Video_Player {
            get {
                return ResourceManager.GetString("Video_Player", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video_was_deleted_from_server!.
        /// </summary>
        public static string Video_was_deleted_from_server {
            get {
                return ResourceManager.GetString("Video_was_deleted_from_server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Videos.
        /// </summary>
        public static string Videos {
            get {
                return ResourceManager.GetString("Videos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View comments left.
        /// </summary>
        public static string View_comments_left {
            get {
                return ResourceManager.GetString("View_comments_left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View, search and delete comments.
        /// </summary>
        public static string View_search_and_delete_comments {
            get {
                return ResourceManager.GetString("View_search_and_delete_comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View, search and delete videos.
        /// </summary>
        public static string View_search_and_delete_videos {
            get {
                return ResourceManager.GetString("View_search_and_delete_videos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View uploaded videos.
        /// </summary>
        public static string View_uploaded_videos {
            get {
                return ResourceManager.GetString("View_uploaded_videos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video downloaded.
        /// </summary>
        public static string Your_video_downloaded {
            get {
                return ResourceManager.GetString("Your_video_downloaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your video uploaded.
        /// </summary>
        public static string Your_video_uploaded {
            get {
                return ResourceManager.GetString("Your_video_uploaded", resourceCulture);
            }
        }
    }
}
